In [1]:
import pandas as pd

books = pd.read_csv("../dataset/books_cleaned.csv")
book_tags = pd.read_csv("../dataset/book_tags.csv")
tags = pd.read_csv("../dataset/tags.csv")

books.head()
tags.head()

   tag_id tag_name
0       0        -
1       1     --1-
2       2    --10-
3       3    --12-
4       4   --122-

In [2]:
book_tags = book_tags.merge(tags, on="tag_id", how="left")
book_tags.head()

   goodreads_book_id  tag_id   count           tag_name
0                  1   30574  167697            to-read
1                  1   11305   37174            fantasy
2                  1   11557   34173          favorites
3                  1    8717   12986  currently-reading
4                  1   33114   12716        young-adult

In [3]:
book_tags = book_tags[["goodreads_book_id", "tag_name"]]

In [4]:
book_tags_grouped = book_tags.groupby("goodreads_book_id")["tag_name"] \
    .apply(lambda x: " ".join(x)) \
    .reset_index()

book_tags_grouped.head()

   goodreads_book_id                                           tag_name
0                  1  to-read fantasy favorites currently-reading yo...
1                  2  to-read currently-reading fantasy favorites ch...
2                  3  to-read favorites fantasy currently-reading yo...
3                  5  favorites fantasy currently-reading young-adul...
4                  6  fantasy young-adult fiction harry-potter owned...

In [5]:
books = books.merge(
    book_tags_grouped,
    left_on="book_id",
    right_on="goodreads_book_id",
    how="left"
)

books.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,content,goodreads_book_id,tag_name
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008,The Hunger Games,...,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,the hunger games the hunger games 1 Suzanne Co...,2767052,favorites currently-reading young-adult fictio...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997,Harry Potter and the Philosopher's Stone,...,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,harry potter and the sorcerers stone harry pot...,3,to-read favorites fantasy currently-reading yo...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005,Twilight,...,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,twilight twilight 1 Stephenie Meyer 2005,41865,young-adult fantasy favorites vampires ya fict...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960,To Kill a Mockingbird,...,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,to kill a mockingbird Harper Lee 1960,2657,classics favorites to-read classic historical-...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925,The Great Gatsby,...,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,the great gatsby F. Scott Fitzgerald 1925,4671,classics favorites fiction classic books-i-own...

In [6]:

books["content_features"] = (
    books["title"] + " " +
    books["authors"] + " " +
    books["tag_name"].fillna("")
)

books[["title", "content_features"]].head()

books.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,content,goodreads_book_id,tag_name,content_features
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008,The Hunger Games,...,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,the hunger games the hunger games 1 Suzanne Co...,2767052,favorites currently-reading young-adult fictio...,the hunger games the hunger games 1 Suzanne Co...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997,Harry Potter and the Philosopher's Stone,...,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,harry potter and the sorcerers stone harry pot...,3,to-read favorites fantasy currently-reading yo...,harry potter and the sorcerers stone harry pot...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005,Twilight,...,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,twilight twilight 1 Stephenie Meyer 2005,41865,young-adult fantasy favorites vampires ya fict...,twilight twilight 1 Stephenie Meyer young-adul...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960,To Kill a Mockingbird,...,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,to kill a mockingbird Harper Lee 1960,2657,classics favorites to-read classic historical-...,to kill a mockingbird Harper Lee classics favo...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925,The Great Gatsby,...,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,the great gatsby F. Scott Fitzgerald 1925,4671,classics favorites fiction classic books-i-own...,the great gatsby F. Scott Fitzgerald classics ...

In [7]:
books["content_features"] = books["content_features"].fillna("")
books["content_features"] = books["content_features"].astype(str)
print(books["content_features"].isnull().sum())

0

In [8]:
books.to_csv("books_genre.csv", index=False)